services:
  dbms:
    build:
      context: ./dbms
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${DBMS_USERNAME}
      POSTGRES_PASSWORD: ${DBMS_PASSWORD}
    volumes:
      - ./dbms/vlpd:/var/lib/postgresql/data

  server:
    depends_on:
      - dbms
    build:
      context: ./server
      args:
        SERVER_SSL_CERT_FILE: ${SERVER_SSL_CERT_FILE}
        SERVER_SSL_PKEY_FILE: ${SERVER_SSL_PKEY_FILE}
      dockerfile: Dockerfile 
    ports:
      - 80:80
      - 443:443
    environment:
      DB_HOST: dbms
      DB_USERNAME: ${DBMS_USERNAME}
      DB_PASSWORD: ${DBMS_PASSWORD}
      DB_NAME: ${DBMS_DATABASE}
      SERVER_NAME: ${SERVER_NAME}
      SERVER_SSL_CERT_FILE: ${SERVER_SSL_CERT_FILE}
      SERVER_SSL_PKEY_FILE: ${SERVER_SSL_PKEY_FILE}
    volumes:
      - ./server/vwh:/var/www/html/

  redis:
    image: redis:alpine

  api:
    depends_on:
      - redis
    build:
      context: ./suggestions-api
      dockerfile: DockerfileAPI
    ports:
      - 8000:8000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  worker:
    depends_on:
      - redis
    build:
      context: ./suggestions-api
      dockerfile: DockerfileWorker
